# Data Pre-Processing 
#### Removing redundant attributes
#### Encoding Categorical values to Vectors
#### Random Sampling of values  
#### Saving sampled values into a csv file

In [3]:
import pandas as pd
from collections import Counter
from sklearn.preprocessing import LabelEncoder
import numpy as np

In [4]:
# Reading the dataset and printing the first 5 objects of the dataset
df = pd.read_csv("PFW_2021_public.nosync/PFW_2021_public.csv")
df.head()

,loc_id,latitude,longitude,subnational1_code,entry_technique,sub_id,obs_id,Month,Day,Year,...,how_many,valid,reviewed,day1_am,day1_pm,day2_am,day2_pm,effort_hrs_atleast,snow_dep_atleast,Data_Entry_Method
0,L12782033,44.574148,-78.205608,CA-ON,/GOOGLE_MAP/ZOOM:15,S79876486,OBS1059258900,1,24,2021,...,1,1,0,0,1,0,1,0.001,5.000,PFW Mobile App v1.1.17
1,L12782033,44.574148,-78.205608,CA-ON,/GOOGLE_MAP/ZOOM:15,S79876486,OBS1059259256,1,24,2021,...,2,1,0,0,1,0,1,0.001,5.000,PFW Mobile App v1.1.17
2,L12782033,44.574148,-78.205608,CA-ON,/GOOGLE_MAP/ZOOM:15,S79876486,OBS1059259639,1,24,2021,...,2,1,0,0,1,0,1,0.001,5.000,PFW Mobile App v1.1.17
3,L12755941,54.136873,-108.687862,CA-SK,/GOOGLE_MAP/ZOOM:17,S76634904,OBS1017001338,11,23,2020,...,2,1,0,0,1,0,1,0.001,15.001,PFW Web 4.1.4
4,L12755941,54.136873,-108.687862,CA-SK,/GOOGLE_MAP/ZOOM:17,S76634904,OBS1017001339,11,23,2020,...,2,1,0,0,1,0,1,0.001,15.001,PFW Web 4.1.4

In [5]:
print(df.columns)

Index(['loc_id', 'latitude', 'longitude', 'subnational1_code',
       'entry_technique', 'sub_id', 'obs_id', 'Month', 'Day', 'Year',
       'PROJ_PERIOD_ID', 'species_code', 'how_many', 'valid', 'reviewed',
       'day1_am', 'day1_pm', 'day2_am', 'day2_pm', 'effort_hrs_atleast',
       'snow_dep_atleast', 'Data_Entry_Method'],
      dtype='object')

In [6]:
#Printing no of unique values of  the dataset

print("Shape :",df.shape)
print(df.nunique(axis = 0))

Shape : (2897105, 22)
loc_id                  17650
latitude                17552
longitude               17554
subnational1_code          65
entry_technique           109
sub_id                 248241
obs_id                2897105
Month                       6
Day                        31
Year                        2
PROJ_PERIOD_ID              1
species_code              563
how_many                  231
valid                       2
reviewed                    2
day1_am                     2
day1_pm                     2
day2_am                     2
day2_pm                     2
effort_hrs_atleast          4
snow_dep_atleast            4
Data_Entry_Method           8
dtype: int64

In [7]:
# Attribute PROJ_PERIOD_ID  is universal and obs_id is completely unique and will both be removed from the dataset

df = df.drop("PROJ_PERIOD_ID",axis=1)
df = df.drop("obs_id",axis=1)
print(df.nunique(axis=0))

loc_id                 17650
latitude               17552
longitude              17554
subnational1_code         65
entry_technique          109
sub_id                248241
Month                      6
Day                       31
Year                       2
species_code             563
how_many                 231
valid                      2
reviewed                   2
day1_am                    2
day1_pm                    2
day2_am                    2
day2_pm                    2
effort_hrs_atleast         4
snow_dep_atleast           4
Data_Entry_Method          8
dtype: int64

In [8]:
# Combining Month,Day and Year into a single attribute

new_column = []
for index,row in df.iterrows():
    # val= str(row[6])+":"+str(row[7])+":"+str(row[8])
    new_column.append(str(row[6])+"-"+str(row[7])+"-"+str(row[8]))

# print(new_column[0:5])
df["date"] = new_column

df["date"].head()

0     1-24-2021
1     1-24-2021
2     1-24-2021
3    11-23-2020
4    11-23-2020
Name: date, dtype: object

In [9]:
#Adding this as the new attribute and removing the Month,Day and Year attribute
df["date"] = pd.to_datetime(df["date"],dayfirst=True)

df = df.drop(["Month","Day","Year"],axis= 1)
df.head()

,loc_id,latitude,longitude,subnational1_code,entry_technique,sub_id,species_code,how_many,valid,reviewed,day1_am,day1_pm,day2_am,day2_pm,effort_hrs_atleast,snow_dep_atleast,Data_Entry_Method,date
0,L12782033,44.574148,-78.205608,CA-ON,/GOOGLE_MAP/ZOOM:15,S79876486,amtspa,1,1,0,0,1,0,1,0.001,5.000,PFW Mobile App v1.1.17,2021-01-24
1,L12782033,44.574148,-78.205608,CA-ON,/GOOGLE_MAP/ZOOM:15,S79876486,blujay,2,1,0,0,1,0,1,0.001,5.000,PFW Mobile App v1.1.17,2021-01-24
2,L12782033,44.574148,-78.205608,CA-ON,/GOOGLE_MAP/ZOOM:15,S79876486,bkcchi,2,1,0,0,1,0,1,0.001,5.000,PFW Mobile App v1.1.17,2021-01-24
3,L12755941,54.136873,-108.687862,CA-SK,/GOOGLE_MAP/ZOOM:17,S76634904,dowwoo,2,1,0,0,1,0,1,0.001,15.001,PFW Web 4.1.4,2020-11-23
4,L12755941,54.136873,-108.687862,CA-SK,/GOOGLE_MAP/ZOOM:17,S76634904,whbnut,2,1,0,0,1,0,1,0.001,15.001,PFW Web 4.1.4,2020-11-23

In [10]:
#After Deciding the categorical attributes in the dataset, we label encode these attributes using LabelEncoder

categorical_attr = ["loc_id","subnational1_code","entry_technique","sub_id","species_code","reviewed","valid","day1_am","day1_pm","day2_pm","day2_am","Data_Entry_Method"]

encoder = LabelEncoder()
df[categorical_attr] = df[categorical_attr].apply(encoder.fit_transform)

df.head()

In [ ]:
#Creating a new column to hold the binned values of attribute how_many

max_val = df["how_many"].max()
min_val =df["how_many"].min()

x = list(range(0,(max_val+10),10))

# print(x)

df["how_many_bins"] = np.digitize(df["how_many"],bins = x)

df[["how_many","how_many_bins"]].head()

   how_many  how_many_bins
0         1              1
1         2              1
2         2              1
3         2              1
4         2              1

In [ ]:
#Sampling 500 objects from original dataset without replacement

 
df_sample =df.sample(500,replace=False)

df_sample.to_csv("Sample_HW1.csv")